import { User, Loan, Budget, Draw, Document, Inspection, WarehouseLine, FundingEvent } from './types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'builder@example.com',
    name: 'John Builder',
    role: 'builder',
    company: 'ABC Construction Co.',
    tenantId: 'tenant-1',
  },
  {
    id: 'user-2',
    email: 'lender@example.com',
    name: 'Sarah Lender',
    role: 'lender',
    company: 'First National Bank',
    tenantId: 'tenant-1',
  },
  {
    id: 'user-3',
    email: 'admin@example.com',
    name: 'Mike Admin',
    role: 'admin',
    tenantId: 'tenant-1',
  },
  {
    id: 'user-4',
    email: 'fundadmin@example.com',
    name: 'Lisa Fund Admin',
    role: 'fund_admin',
    tenantId: 'tenant-1',
  },
];

export const mockLoans: Loan[] = [
  {
    id: 'loan-1',
    loanNumber: 'CL-2024-001',
    borrowerName: 'Smith Family Trust',
    propertyAddress: '123 Main Street',
    city: 'Austin',
    state: 'TX',
    zipCode: '78701',
    loanAmount: 500000,
    currentBalance: 350000,
    status: 'active',
    builderId: 'user-1',
    builderName: 'ABC Construction Co.',
    startDate: '2024-01-15',
    expectedCompletionDate: '2024-08-30',
    currentPhase: 'Framing',
    progress: 45,
  },
  {
    id: 'loan-2',
    loanNumber: 'CL-2024-002',
    borrowerName: 'Johnson Development LLC',
    propertyAddress: '456 Oak Avenue',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75201',
    loanAmount: 750000,
    currentBalance: 600000,
    status: 'active',
    builderId: 'user-1',
    builderName: 'ABC Construction Co.',
    startDate: '2024-02-01',
    expectedCompletionDate: '2024-10-15',
    currentPhase: 'Foundation',
    progress: 25,
  },
  {
    id: 'loan-3',
    loanNumber: 'CL-2024-003',
    borrowerName: 'Williams Custom Homes',
    propertyAddress: '789 Pine Road',
    city: 'Houston',
    state: 'TX',
    zipCode: '77001',
    loanAmount: 650000,
    currentBalance: 200000,
    status: 'active',
    builderId: 'user-1',
    builderName: 'ABC Construction Co.',
    startDate: '2023-11-10',
    expectedCompletionDate: '2024-06-20',
    currentPhase: 'Finishing',
    progress: 75,
  },
];

export const mockBudgets: Budget[] = [
  {
    id: 'budget-1',
    loanId: 'loan-1',
    version: 1,
    totalBudget: 500000,
    lines: [
      {
        id: 'line-1',
        category: 'Site Work',
        description: 'Excavation, grading, utilities',
        budgetedAmount: 50000,
        paidToDate: 45000,
        pendingAmount: 5000,
        remainingAmount: 0,
        percentageComplete: 100,
      },
      {
        id: 'line-2',
        category: 'Foundation',
        description: 'Concrete foundation and footings',
        budgetedAmount: 75000,
        paidToDate: 75000,
        pendingAmount: 0,
        remainingAmount: 0,
        percentageComplete: 100,
      },
      {
        id: 'line-3',
        category: 'Framing',
        description: 'Lumber, trusses, framing labor',
        budgetedAmount: 120000,
        paidToDate: 60000,
        pendingAmount: 30000,
        remainingAmount: 30000,
        percentageComplete: 50,
      },
      {
        id: 'line-4',
        category: 'Roofing',
        description: 'Shingles, gutters, flashing',
        budgetedAmount: 45000,
        paidToDate: 0,
        pendingAmount: 0,
        remainingAmount: 45000,
        percentageComplete: 0,
      },
      {
        id: 'line-5',
        category: 'Electrical',
        description: 'Wiring, fixtures, panel',
        budgetedAmount: 35000,
        paidToDate: 15000,
        pendingAmount: 0,
        remainingAmount: 20000,
        percentageComplete: 43,
      },
      {
        id: 'line-6',
        category: 'Plumbing',
        description: 'Rough-in, fixtures, water heater',
        budgetedAmount: 40000,
        paidToDate: 20000,
        pendingAmount: 0,
        remainingAmount: 20000,
        percentageComplete: 50,
      },
      {
        id: 'line-7',
        category: 'HVAC',
        description: 'Ductwork, unit, installation',
        budgetedAmount: 35000,
        paidToDate: 0,
        pendingAmount: 0,
        remainingAmount: 35000,
        percentageComplete: 0,
      },
      {
        id: 'line-8',
        category: 'Interior Finishes',
        description: 'Drywall, paint, flooring',
        budgetedAmount: 60000,
        paidToDate: 0,
        pendingAmount: 0,
        remainingAmount: 60000,
        percentageComplete: 0,
      },
      {
        id: 'line-9',
        category: 'Exterior Finishes',
        description: 'Siding, paint, trim',
        budgetedAmount: 35000,
        paidToDate: 0,
        pendingAmount: 0,
        remainingAmount: 35000,
        percentageComplete: 0,
      },
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-03-20',
  },
];

export const mockDraws: Draw[] = [
  {
    id: 'draw-1',
    loanId: 'loan-1',
    drawNumber: 1,
    requestedDate: '2024-01-20',
    requestedBy: 'John Builder',
    status: 'funded',
    totalRequested: 50000,
    totalApproved: 50000,
    lineItems: [
      {
        id: 'item-1',
        budgetLineId: 'line-1',
        category: 'Site Work',
        description: 'Excavation and grading completed',
        requestedAmount: 50000,
        approvedAmount: 50000,
        status: 'paid',
      },
    ],
    documents: [],
    reviewedBy: 'Sarah Lender',
    reviewedAt: '2024-01-22',
  },
  {
    id: 'draw-2',
    loanId: 'loan-1',
    drawNumber: 2,
    requestedDate: '2024-02-05',
    requestedBy: 'John Builder',
    status: 'funded',
    totalRequested: 75000,
    totalApproved: 75000,
    lineItems: [
      {
        id: 'item-2',
        budgetLineId: 'line-2',
        category: 'Foundation',
        description: 'Foundation pour completed',
        requestedAmount: 75000,
        approvedAmount: 75000,
        status: 'paid',
      },
    ],
    documents: [],
    reviewedBy: 'Sarah Lender',
    reviewedAt: '2024-02-07',
  },
  {
    id: 'draw-3',
    loanId: 'loan-1',
    drawNumber: 3,
    requestedDate: '2024-03-15',
    requestedBy: 'John Builder',
    status: 'under_review',
    totalRequested: 90000,
    lineItems: [
      {
        id: 'item-3',
        budgetLineId: 'line-3',
        category: 'Framing',
        description: '50% framing complete - first floor',
        requestedAmount: 60000,
        status: 'pending',
      },
      {
        id: 'item-4',
        budgetLineId: 'line-5',
        category: 'Electrical',
        description: 'Rough-in electrical work',
        requestedAmount: 15000,
        status: 'pending',
      },
      {
        id: 'item-5',
        budgetLineId: 'line-6',
        category: 'Plumbing',
        description: 'Rough-in plumbing work',
        requestedAmount: 15000,
        status: 'pending',
      },
    ],
    documents: [
      {
        id: 'doc-1',
        name: 'invoice_framing.pdf',
        type: 'application/pdf',
        uploadedBy: 'John Builder',
        uploadedAt: '2024-03-15',
        size: 245760,
        url: '#',
        category: 'invoice',
      },
      {
        id: 'doc-2',
        name: 'progress_photo_1.jpg',
        type: 'image/jpeg',
        uploadedBy: 'John Builder',
        uploadedAt: '2024-03-15',
        size: 1024000,
        url: '#',
        category: 'photo',
      },
    ],
    inspectionId: 'inspection-1',
  },
  {
    id: 'draw-4',
    loanId: 'loan-1',
    drawNumber: 4,
    requestedDate: '2024-03-25',
    requestedBy: 'John Builder',
    status: 'draft',
    totalRequested: 30000,
    lineItems: [
      {
        id: 'item-6',
        budgetLineId: 'line-3',
        category: 'Framing',
        description: 'Remaining framing work',
        requestedAmount: 30000,
        status: 'pending',
      },
    ],
    documents: [],
  },
];

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    name: 'invoice_framing.pdf',
    type: 'application/pdf',
    uploadedBy: 'John Builder',
    uploadedAt: '2024-03-15',
    size: 245760,
    url: '#',
    category: 'invoice',
  },
  {
    id: 'doc-2',
    name: 'progress_photo_1.jpg',
    type: 'image/jpeg',
    uploadedBy: 'John Builder',
    uploadedAt: '2024-03-15',
    size: 1024000,
    url: '#',
    category: 'photo',
  },
  {
    id: 'doc-3',
    name: 'contract_signed.pdf',
    type: 'application/pdf',
    uploadedBy: 'Sarah Lender',
    uploadedAt: '2024-01-10',
    size: 512000,
    url: '#',
    category: 'contract',
  },
];

export const mockInspections: Inspection[] = [
  {
    id: 'inspection-1',
    loanId: 'loan-1',
    drawId: 'draw-3',
    inspectorName: 'Robert Inspector',
    scheduledDate: '2024-03-18',
    completedDate: '2024-03-18',
    status: 'completed',
    findings: 'Framing work is 50% complete and meets code requirements. Electrical and plumbing rough-in visible and properly installed.',
    photos: ['photo1.jpg', 'photo2.jpg'],
    approved: true,
  },
];

export const mockWarehouseLines: WarehouseLine[] = [
  {
    id: 'wh-1',
    name: 'Primary Warehouse Line',
    totalLimit: 10000000,
    currentUtilization: 6500000,
    availableCapacity: 3500000,
    interestRate: 5.25,
    status: 'active',
    loans: ['loan-1', 'loan-2', 'loan-3'],
  },
];

export const mockFundingEvents: FundingEvent[] = [
  {
    id: 'fund-1',
    drawId: 'draw-1',
    loanId: 'loan-1',
    amount: 50000,
    fundedDate: '2024-01-25',
    warehouseLineId: 'wh-1',
    interestReserve: 2500,
    spread: 2.5,
    status: 'completed',
  },
  {
    id: 'fund-2',
    drawId: 'draw-2',
    loanId: 'loan-1',
    amount: 75000,
    fundedDate: '2024-02-10',
    warehouseLineId: 'wh-1',
    interestReserve: 3750,
    spread: 2.5,
    status: 'completed',
  },
];

// Helper functions to get data by ID
export const getLoanById = (id: string) => mockLoans.find(loan => loan.id === id);
export const getBudgetByLoanId = (loanId: string) => mockBudgets.find(budget => budget.loanId === loanId);
export const getDrawsByLoanId = (loanId: string) => mockDraws.filter(draw => draw.loanId === loanId);
export const getUserByRole = (role: string) => mockUsers.find(user => user.role === role);

